name: flutter_security_toolkit
description: "A Mobile Security Toolkit providing easy API to check device status (Root, Hooks, Simulator, etc)"
version: 1.0.0
homepage: https://github.com/EXXETA/Flutter-Security-Toolkit

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_security_toolkit
        pluginClass: FlutterSecurityToolkitPlugin
      ios:
        pluginClass: FlutterSecurityToolkitPlugin
